#!/usr/bin/env node
/**
 * Publish a canvas into the project's own repo as a self-contained HTML record.
 *
 * THE SEAM. Studio and flow must not depend on each other, so nothing is
 * imported across the boundary in either direction — this writes an ordinary
 * file into an ordinary repo. The loop closes on the other side: the pull
 * request that lands the file is the ref you put in `exploration.json`, and
 * Studio reads its state back through `gh`.
 *
 *   npm run publish -- <canvas-id> --to ../ripe/design
 *   npm run publish -- --list
 *
 * The output is a STATIC snapshot. Prototypes are live React and none of that
 * survives the render; the page says so rather than letting a reader find out
 * by tapping something inert.
 */
import { execFileSync } from 'node:child_process'
import { mkdirSync, readFileSync, readdirSync, writeFileSync, existsSync } from 'node:fs'
import { basename, join, resolve } from 'node:path'
import { marked } from 'marked'

const ROOT = new URL('..', import.meta.url).pathname
const SSR_DIR = join(ROOT, '.publish/ssr')
const CLIENT_DIR = join(ROOT, '.publish/client')

const argv = process.argv.slice(2)
const wants = (flag) => argv.includes(flag)
const valueOf = (flag) => {
  const i = argv.indexOf(flag)
  return i >= 0 ? argv[i + 1] : undefined
}
const canvasId = argv.find((a) => !a.startsWith('--') && argv[argv.indexOf(a) - 1] !== '--to')

function build() {
  console.log('  building…')
  execFileSync(
    'npx',
    ['vite', 'build', '--ssr', 'scripts/render-canvas.tsx', '--outDir', '.publish/ssr', '--logLevel', 'warn'],
    { cwd: ROOT, stdio: 'inherit' },
  )
  execFileSync('npx', ['vite', 'build', '--outDir', '.publish/client', '--logLevel', 'warn'], {
    cwd: ROOT,
    stdio: 'inherit',
  })
}

/** Every style the app has, from the client build — one file, already bundled. */
function collectCss() {
  const dir = join(CLIENT_DIR, 'assets')
  if (!existsSync(dir)) throw new Error('client build produced no assets')
  return readdirSync(dir)
    .filter((f) => f.endsWith('.css'))
    .map((f) => readFileSync(join(dir, f), 'utf8'))
    .join('\n')
}

async function loadRenderer() {
  const entry = readdirSync(SSR_DIR).find((f) => f.startsWith('render-canvas') && f.endsWith('.js'))
  if (!entry) throw new Error('ssr build produced no render-canvas entry')
  return import(join(SSR_DIR, entry))
}

function esc(s) {
  return String(s).replace(/[&<>]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;' })[c])
}

function page(c, css) {
  const stamp = new Date().toISOString().slice(0, 10)

  const sections = c.sections
    .map(
      (s) => `
  <section class="pb-section">
    ${s.title ? `<h2>${esc(s.title)}</h2>` : ''}
    ${s.note ? `<p class="pb-note">${esc(s.note)}</p>` : ''}
    ${s.rows
      .map(
        (row) => `<div class="pb-row">${row
          .map(
            (f) => `
      <figure class="pb-frame">
        <figcaption class="pb-name">${esc(f.name)}</figcaption>
        <div class="pb-shot" style="width:${f.width}px;height:${f.height}px">${f.html}</div>
        ${f.caption ? `<figcaption class="pb-cap">${esc(f.caption)}</figcaption>` : ''}
      </figure>`,
          )
          .join('')}</div>`,
      )
      .join('')}
  </section>`,
    )
    .join('')

  return `<!doctype html>
<!--
  Published from Studio — a static record of a design exploration.

  Generated by studio/scripts/publish.mjs on ${stamp} from canvas "${c.id}".
  Regenerating overwrites this file, so edit the exploration in Studio rather
  than this page.

  The frames below are rendered markup, not screenshots: diffable, and they
  scale with the reader's zoom. They are also INERT — the live prototypes are
  interactive and none of that survives a static render.
-->
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${esc(c.title)}</title>
<style>
${css}

/* --- the published record's own chrome ------------------------------------ */
body { background: #f6f6f4; color: #1f1f1e; }
.pb { max-width: 1180px; margin: 0 auto; padding: 46px 28px 120px; }
.pb-eyebrow { font-size: 12px; letter-spacing: .09em; text-transform: uppercase; color: #8b8a86; margin: 0 0 10px; }
.pb h1 { font-size: 30px; font-weight: 650; letter-spacing: -.028em; margin: 0 0 12px; }
.pb-question { font-size: 17px; font-style: italic; color: #55534f; margin: 0 0 18px; max-width: 70ch; }
.pb-lede { font-size: 15.5px; line-height: 1.65; color: #45443f; margin: 0 0 10px; max-width: 74ch; }
.pb-meta { font-size: 12.5px; color: #8b8a86; margin: 22px 0 0; }
.pb-static { margin: 26px 0 0; padding: 12px 16px; border-left: 2px solid #d8d7d2; font-size: 13.5px; color: #6a6863; }
.pb-section { margin: 54px 0 0; }
.pb-section h2 { font-size: 13px; font-weight: 650; letter-spacing: .07em; text-transform: uppercase; color: #8b8a86; margin: 0 0 8px; }
.pb-note { font-size: 15px; line-height: 1.62; color: #45443f; margin: 0 0 22px; max-width: 74ch; }
.pb-row { display: flex; gap: 40px; flex-wrap: wrap; align-items: flex-start; }
.pb-frame { margin: 0; display: flex; flex-direction: column; gap: 12px; align-items: flex-start; }
.pb-name { font-size: 14px; font-weight: 600; }
.pb-cap { font-size: 13px; line-height: 1.5; color: #55534f; max-width: 420px; }
.pb-shot { overflow: hidden; }
.pb-doc { margin: 54px 0 0; max-width: 74ch; font-size: 15px; line-height: 1.66; color: #45443f; }
.pb-doc h1 { font-size: 19px; margin: 28px 0 8px; }
.pb-doc h2 { font-size: 15.5px; margin: 26px 0 8px; color: #1f1f1e; }
.pb-doc table { border-collapse: collapse; width: 100%; font-size: 14px; }
.pb-doc th, .pb-doc td { text-align: left; padding: 7px 12px 7px 0; border-bottom: 1px solid #e4e3de; vertical-align: top; }
.pb-doc code { background: #ecebe6; border-radius: 4px; padding: 1.5px 5px; font-size: .88em; }
</style>
</head>
<body>
<main class="pb">
  <p class="pb-eyebrow">${esc(c.projectName)}${c.who ? ` · ${esc(c.who)}` : ''}</p>
  <h1>${esc(c.title)}</h1>
  ${c.question ? `<p class="pb-question">${esc(c.question)}</p>` : ''}
  ${c.lede ? `<p class="pb-lede">${esc(c.lede)}</p>` : ''}

  <p class="pb-static">
    A static record. The frames are rendered markup rather than screenshots, but
    they are inert — the live, interactive version is in Studio at
    <code>#/p/${esc(c.projectId)}</code>.
  </p>
${sections}

  ${c.brief ? `<div class="pb-doc"><h1>Brief</h1>${marked.parse(c.brief)}</div>` : ''}
  ${c.notes ? `<div class="pb-doc">${marked.parse(c.notes)}</div>` : ''}

  <p class="pb-meta">Published from Studio on ${stamp} · canvas <code>${esc(c.id)}</code></p>
</main>
</body>
</html>
`
}

// --- run ---------------------------------------------------------------------

build()
const renderer = await loadRenderer()

if (wants('--list') || !canvasId) {
  const all = renderer.listCanvases()
  console.log('\nCanvases available to publish:\n')
  for (const c of all) console.log(`  ${c.id}\n    ${c.title}\n`)
  console.log('  npm run publish -- <canvas-id> --to ../<project>/design\n')
  process.exit(canvasId ? 0 : 1)
}

const rendered = renderer.renderCanvas(canvasId)
const target = valueOf('--to') ?? `../${rendered.projectId}/design`
const dir = resolve(ROOT, target)

if (!existsSync(dir)) {
  if (!wants('--mkdir')) {
    console.error(
      `\n✗ ${dir} does not exist.\n  Check the path, or pass --mkdir to create it.\n`,
    )
    process.exit(1)
  }
  mkdirSync(dir, { recursive: true })
}

const name = `${basename(rendered.id)}.html`
const out = join(dir, name)
writeFileSync(out, page(rendered, collectCss()))

const frames = rendered.sections.reduce((n, s) => n + s.rows.flat().length, 0)
console.log(`\n✓ ${out}`)
console.log(`  ${frames} frame(s) from "${rendered.title}"`)
console.log(`  Commit it in that repo; put the resulting PR in exploration.json.\n`)
